@rootURL = http://localhost:5286

GET {{rootURL}}/weatherforecast/
Accept: application/json

###

GET {{rootURL}}/api/book
Accept: application/json


###

GET {{rootURL}}/api/book/2
Accept: application/json

###
POST {{rootURL}}/api/book
Content-Type: application/json

{
  "id": 6,
  "title": "C# Unlocked",
  "author": "Alen",
  "yearPublished": 2024
}

###

PUT {{rootURL}}/api/book/6
Content-Type: application/json

{
  "id": 6,
  "title": "MobyDick",
  "author": "Alen",
  "yearPublished": 1851
}

###
DELETE {{rootURL}}/api/book/5
Accept: application/json